### PR TITLE
feature/dark crystal secrets

### PR DESCRIPTION
**Pull request by KGibb8**
Referencing https://github.com/blockades/scuttle-dark-crystal/issues/45

- [x] Extract secrets-wrapper into a new package called dark-crystal-secrets
- [x] Require that package into scuttle-dark-crystal
- [x] Bump scuttle-dark-crystal version
- [x] Create new repository called dark-crystal-secrets-api
- [x] Write tests for the API end-points
- [x] Create a HTTP server and open up the end-points
- [x] Integrate with the relevant functions from dark-crystal-secrets and format JSON responses.
- [x] Ensure effective error handling and clear responses
- [x] Clear explanation of when to use the API
- [x] Docker and docker-compose
- [x] Swagger API documentation
- [x] Make port and domain configurable
- [x] new tests for `verify` function in `dark-crystal-secrets`
- [x] documentation for `dark-crystal-secrets`

https://github.com/blockades/dark-crystal-secrets
https://github.com/blockades/dark-crystal-secrets-api/

### CODE REVIEW

**Comment by KGibb8** [comment]
Exposed a broader issue in how we're handling shard verification here https://github.com/blockades/dark-crystal-secrets/issues/1

**Comment by KGibb8** [comment]
@ameba23 @mixmix please review!

**Comment by mixmix** [comment]
Looks good. To clarify, that big checklist is not what this PR is. This PR is just extracting the secrets lib, which feels like a good move.

I went and had a review of that, and added a little to the docs - https://github.com/blockades/dark-crystal-secrets/pull/2
(I noticed as a standalone API it was hard to see how to use all the methods together e.g. difference between packing and sharing ...)

**Comment by mixmix** [comment]
cc @KGibb8

**Comment by KGibb8** [comment]
> To clarify, that big checklist is not what this PR is. This PR is just extracting the secrets lib, which feels like a good move.

That was for the sake of myself (and Gitcoin).

I will go ahead and merge.

We'll need a version bump at some point soon.

**Pull request merged**
